service: mutant-handler

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:ListQueues"
      Resource: "arn:aws:sqs:us-east-1:393478962179:mutant-sqs"

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  receiver:
    handler: src/handler.save
    events:
      - sqs: arn:aws:sqs:us-east-1:393478962179:mutant-sqs
